import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import { decrypt } from "../login/session";
import "../globals.css";
import {SignOutButton} from "@/commons/signout";
import ThemeSwitcher from "@/commons/theme-switcher";
import MenuComponent from "../../commons/menu.component";
import { menuLinks } from "../api/v1/mocks";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const session = await decrypt(cookieStore.get("session")?.value);


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <div className="h-screen w-60 fixed top-0 left-0 bg-gray-400 dark:bg-gray-800 text-gray-800 dark:text-white flex flex-col justify-between">
            <div className="p-4">
              <div className="flex items-center justify-between">
                <h1 className="text-xl font-bold">Menu</h1>
                <ThemeSwitcher />
              </div>
              <div className="mt-4 space-y-4">
                {session && <MenuComponent session={session} pages={menuLinks}/> }
              </div> 
            </div>

            {/* Client component boundary */}
            <div className="p-4">
              <SignOutButton />
            </div>
          </div>
          <div className="ml-60 flex-1 p-4">{children}</div>
        </div>
      </body>
    </html>
  );
}

